### ISSUE TITLE
Smoothscroll breaks on OSX Sierra

### ISSUE THREAD

**Issue by TiagoDeSousa** [galambalazs/smoothscroll-for-websites#48] opened 2016-10-07 10:39 UTC
Since I updated to OSX Sierra smoothscroll acts a bit weird on Chrome on mousewheel.

**Comment by sergiokag** [comment] 2016-10-23 08:56
I have the same experience with OS X El capitan

**Comment by gblazex** [comment] 2016-11-04 11:39
just chrome or safari too?

**Comment by TiagoDeSousa** [comment] 2016-11-04 18:16
It happens in both to me.

**Comment by gblazex** [comment] 2016-11-05 18:16
Can you do a Quick Time screen recording for me that showcases what you guys mean by weird.

Thanks

**Comment by gblazex** [comment] 2016-11-25 10:42
duplicate of https://github.com/galambalazs/smoothscroll-for-websites/issues/16

**Closed as completed by gblazex** 2016-11-25 10:42 UTC
